export * from './adicion.repository';
export * from './alumno.repository';
export * from './cambio.repository';
export * from './campus.repository';
export * from './carrera.repository';
export * from './confirmacion.repository';
export * from './docente.repository';
export * from './matricula.repository';
export * from './retiro.repository';
