export * from './alumno.model';
export * from './docente.model';
export * from './campus.model';
export * from './carrera.model';
export * from './matricula.model';
export * from './confirmacion.model';
export * from './adicion.model';
export * from './cambio.model';
export * from './retiro.model';
